services:
    twig.extension.parent_template:
        class: AK\TwigExtensionsBundle\Twig\ParentTemplateExtension
        arguments:
            - %ak_twig_extensions.parent_templates%
            - @?request
        tags:
            - {name: twig.extension}
