services:
    twig.extension.parent_template:
        class: AK\TwigExtensionsBundle\Twig\ParentTemplateExtension
        arguments:
            - %ak_twig_extensions.parent_templates%
        calls:
            - [setRequest, [@request_stack]]
        tags:
            - {name: twig.extension}
